Develop
DinaraYusupova/Sprint_4 pull request #1
Opened 2022-09-28 21:12 UTC by DinaraYusupova

Финальный проект + первые 2 задания из дополнительных

2022-09-28 21:16 UTC, DinaraYusupova commented
Привет! первый коммит "Main part of test program for sprint 4" делала для себя, чтобы код между ПК переносить, актуален соответственно второй финальный "Final project Sprint 4"

2022-09-29 20:31 UTC, pavel-ulan requested changes
Коммитов можешь делать сколько угодно =) важно только последнее состояние. Хотя на некоторых проектах что бы не было длинной истории коммитов используют rebase и squash 
Теперь по работе:
- посмотри что принято, а что нет коммитить в репозиторий (так .idea в реп не коммитят).
- это конечно здорово, что ты сделала в 2 раза больше работы, но не надо было разносить тесты на тесты для одного браузера и для другого. Это должно настраиваться или в конфиге или в предусловии. (если у тебя будет задача сделать тест для последних 10 версий какого-то браузера, ты будешь делать 10 тестов?).

Почисти репозиторий от лишних файлов, исправь работу согласно комментов, убери дублирующиеся тесты и сделай возможность выбора браузера.

2022-09-29 20:31 UTC, pavel-ulan commented on src/main/java/pageDescription/HomePageScooter.java
> +    private final String TEXT_AVAILABLE_DISTANCE = "Да, обязательно. Всем самокатов! И Москве, и Московской области.";
Почему тебе так импонируют константы?

2022-09-29 20:31 UTC, pavel-ulan commented on src/main/java/pageDescription/orderPage/OrderScooterAboutRent.java
> +            System.out.println("Некорректный срок аренды, задайте срок аренды числом от 1 до 7");
ну есть же case для таких случаев. можно enum использовать. Но точно не такой каскад из if else. Переделай пожалуйста.

2022-09-29 20:31 UTC, pavel-ulan commented on src/test/java/testsForFirefox/ClickOnLogo.java
> +    // Тест не имеет смысла, т.к. FireFox прекратил поддержку поиска Яндекса, о чем вывесил банер при переходе на страницу Яндекса. Поэтому тест падает.
Тест имеет смысл в любом случае. Тесты для того и тесты, что бы находить ошибки. В ТЗ (задании) есть условие, которое надо проверить. Поддержка (или отказ от нее) встроенного поиска яндекса никак на это не влияет. Точно так же как и редирект с бывшей yandex.ru на страницу дзена. 
Твоя задача, сделать тест согласно условию (ну и если мы говорим про реальный проект, то потом предоставить отчет, почему он упал и т.д.).

2022-09-29 21:04 UTC, DinaraYusupova commented
Привет! Подскажи про константы, вроде в видео нам говорили, что надо вообще стараться максимально закрывать переменные, чтобы быть уверенными, что в коде они не изменятся (если этого не предполагается). т.е. сначала мы пишем все максимально privat final, а потом уже потихоньку их открываем, если это требуется. Подскажи как правильно? final делать только константы вроде π в математике, или все подряд, а потом убирать если хочу менять значение в коде?

2022-10-03 09:42 UTC, DinaraYusupova commented
Привет! Переименовала переменные, настройку браузера вынесла в класс BaseTest, удалила лишнее с репозитория, изучила case и переделала методы с выбором одного из вариантов под case. Посмотри, пожалуйста, когда будет время

2022-10-03 16:30 UTC, pavel-ulan commented
> Привет! Подскажи про константы, вроде в видео нам говорили, что надо вообще стараться максимально закрывать переменные, чтобы быть уверенными, что в коде они не изменятся (если этого не предполагается). т.е. сначала мы пишем все максимально privat final, а потом уже потихоньку их открываем, если это требуется. Подскажи как правильно? final делать только константы вроде π в математике, или все подряд, а потом убирать если хочу менять значение в коде?

Не думаю, что вам говорили делать их константами. Закрывать - да, это факт. Потом смотреть, что должно быть доступно из вне и открывать по необходимости. Тут все верно. Но делать все поля final неправильно. Не думаю, что тут хороший пример про π будет, но если совсем образно, то да. Обычно в константы выносят какие-то тестовые данные (фраза подтвержденного заказа для данного задания например). Т.е. `private final String TEXT_AVAILABLE_DISTANCE = "Да, обязательно. Всем самокатов! ` это норм. Но делать final локаторы, это неправильно. Локаторы это часть страницы, создавая объект страницы ты их инициализируешь. Я не смогу сейчас в 2х словах объяснить где их уместно применять, а где нет в целом, но надеюсь в рамках этого задания мне удалось рассказать =)

2022-10-03 16:31 UTC, pavel-ulan approved these changes
Да, так лучше =)

2022-10-03 16:31 UTC, pavel-ulan commented on src/main/java/pageDescription/orderPage/OrderScooterAboutRent.java
> +        }
Значительно лучше =)

2022-10-04 21:01 UTC, merged